smartcoop/design-library

src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/TableOfContent/TableOfContentHtmlGenerator.cs

Due to bad conflict resolution

Resolve incrementation error

---

src/Smart.Design.Razor/Extensions/DependencyRegistration.cs
src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/Constants/TagNames.cs
src/Smart.Design.Razor/TagHelpers/TableOfContent/TableOfContentTagHelper.cs
src/Smart.Design.Razor/TagHelpers/Titles/PageTitle/IPageTitleHtmlGenerator.cs
src/Smart.Design.Razor/TagHelpers/Titles/PageTitle/PageTitleHtmlGenerator.cs
src/Smart.Design.Razor/TagHelpers/Titles/PageTitle/PageTitleTagHelper.cs

https://smartjira.atlassian.net/browse/DNET-65
* Correct documentation error
* Add page title component
* Increment package versioning

Add page title component

---

src/Smart.Design.Razor/TagHelpers/Buttons/ButtonBackToTop/ButtonBackToTopHtmlGenerator.cs

https://smartjira.atlassian.net/browse/DNET-83

Add accessibility label to back to top button

---

src/Smart.Design.Razor/TagHelpers/Alert/AlertHtmlGenerator.cs

[JIRA description](https://smartjira.atlassian.net/browse/DNET-85)
Adapt alert tag to accept html in message
Co-authored-by: ChMelissa <chm@smart.coop>
Co-authored-by: CelineMarique <mar@smart.coop>
https://design.smart.coop/examples/template-examples/terms-and-conditions--acceptation.html

Adapt alert tag to accept html in message

---

src/Smart.Design.Razor/Resources/Translations.Designer.cs
src/Smart.Design.Razor/Resources/Translations.fr.resx
src/Smart.Design.Razor/Resources/Translations.resx
src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/Header/HeaderHtmlGenerator.cs

Header > Language menu
Delete LanguageChoice
Put p tag when it is current language
[JIRA description](https://smartjira.atlassian.net/browse/CURU-50)
Co-authored-by: ChMelissa [chm@smart.coop](mailto:chm@smart.coop)
Co-authored-by: CelineMarique [mar@smart.coop](mailto:mar@smart.coop)
https://design.smart.coop/examples/template-examples/terms-and-conditions--acceptation.html

Update header tag

---

src/Smart.Design.Razor/TagHelpers/TableOfContent/TableOfContentHtmlGenerator.cs
src/Smart.Design.Razor/wwwroot/css/main.css

[JIRA description](https://smartjira.atlassian.net/browse/CURU-41)
Add 2 first element to table of content without number
https://design.smart.coop/examples/template-examples/terms-and-conditions--acceptation.html#preambule

Update table of content tag

---

src/Smart.Design.Razor/Extensions/DependencyRegistration.cs
src/Smart.Design.Razor/Resources/Translations.Designer.cs
src/Smart.Design.Razor/Resources/Translations.fr.resx
src/Smart.Design.Razor/Resources/Translations.resx
src/Smart.Design.Razor/TagHelpers/AcceptanceCheckbox/AcceptanceCheckboxHtmlGenerator.cs
src/Smart.Design.Razor/TagHelpers/AcceptanceCheckbox/AcceptanceCheckboxStyle.cs
src/Smart.Design.Razor/TagHelpers/AcceptanceCheckbox/AcceptanceCheckboxTagHelper.cs
src/Smart.Design.Razor/TagHelpers/AcceptanceCheckbox/IAcceptanceCheckboxHtmlGenerator.cs
src/Smart.Design.Razor/TagHelpers/Constants/TagNames.cs

[JIRA description](https://smartjira.atlassian.net/browse/DNET-72)
Create acceptance checkbox tag
Co-authored-by: ChMelissa [chm@smart.coop](mailto:chm@smart.coop)
Co-authored-by: CelineMarique [mar@smart.coop](mailto:mar@smart.coop)

Create acceptance checkbox tag

---

src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/AcceptanceCheckbox/AcceptanceCheckboxHtmlGenerator.cs
src/Smart.Design.Razor/TagHelpers/AcceptanceCheckbox/AcceptanceCheckboxTagHelper.cs

Fix class of acceptance checkbox tag
Co-authored-by: Nasseira Tahtah <tan@smart.coop>

Fix class of acceptance checkbox tag

---

src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/AcceptanceCheckbox/AcceptanceCheckboxHtmlGenerator.cs

[Acceptance checkBox] Fix button css class

---

src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/Header/HeaderHtmlGenerator.cs
src/Smart.Design.Razor/TagHelpers/Header/HeaderTagHelper.cs
src/Smart.Design.Razor/TagHelpers/Header/IHeaderHtmlGenerator.cs

Fix logout link
https://smartjira.atlassian.net/browse/CURU-39
Co-authored-by: Nasseira Tahtah <tan@smart.coop>

[Header tag] Fix logout link

---

src/Smart.Design.Razor/Resources/Translations.Designer.cs
src/Smart.Design.Razor/Resources/Translations.nl.resx
src/Smart.Design.Razor/Resources/Translations.resx
src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/AcceptanceCheckbox/AcceptanceCheckboxHtmlGenerator.cs

https://smartjira.atlassian.net/browse/CURU-39
Co-authored-by: Nasseira Tahtah <tan@smart.coop>

Add nl resources translation

---

src/Smart.Design.Razor/TagHelpers/Header/HeaderHtmlGenerator.cs
src/Smart.Design.Razor/TagHelpers/Header/HeaderTagHelper.cs
src/Smart.Design.Razor/TagHelpers/Header/IHeaderHtmlGenerator.cs

Add logopath parameter
https://smartjira.atlassian.net/browse/CURU-39

[Header tag] Add logopath parameter

---

src/Smart.Design.Razor/Smart.Design.Razor.csproj

Update package version

---

src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/SideMenu/SideMenuTagHelper.cs

The div `c-app-layout-inner__sidebar u-position-fixed`  must englobe the side menu and admin search menu

Adapt side menu

---

src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/wwwroot/css/main.css

* update css
* update package version
Co-authored-by: CelineMarique <mar@smart.coop>
Co-authored-by: ChMelissa <chm@smart.coop>
Co-authored-by: Nasseira Tahtah <tan@smart.coop>

Update main css

---

src/Smart.Design.Razor/Extensions/AttributeHelperExtensions.cs
src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/Elements/Checkbox/CheckboxHtmlGenerator.cs
src/Smart.Design.Razor/TagHelpers/Elements/Checkbox/CheckboxTagHelper.cs
src/Smart.Design.Razor/TagHelpers/Elements/Checkbox/ICheckboxHtmlGenerator.cs

Accept custom attributes
https://smartjira.atlassian.net/browse/CURU-94

[Chexkbox] Accept custom attributes

---

src/Smart.Design.Razor/Smart.Design.Razor.csproj
src/Smart.Design.Razor/TagHelpers/Header/HeaderHtmlGenerator.cs

Consider language on documetation and contact link in help menu
Update package
https://smartjira.atlassian.net/browse/BLIP-6567

[Header] Consider language on documetation and contact link

---

src/Smart.Design.Console.Generator/Smart.Design.Console.Generator.csproj
src/Smart.Design.Console.Generator/appsettings.json
src/Smart.Design.Showcase.WebApp/Pages/Components/Pagination/Pagination.cshtml

[Refactor path for file generation](https://smartjira.atlassian.net/browse/BLIP-6755)
Change relative path of file generator following merging of repositories

Change relative path for console generator

---

Dockerfile

Hotfix for wrong Dockerfile path

Fix broken path

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Components/ButtonBackToTop/ButtonBackToTop.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_Layout.cshtml

button back to top: complete

---

pull_request_template.md

Proposal for a new PR template

---

pull_request_template.md

Detailed list of changes/actions
* Change with Victor's proposal

 [Library/Showcase]  Improve Pull Request template

---

src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/TagHelpers/Header/HeaderHtmlGenerator.cs

https://smartjira.atlassian.net/browse/CFA-599
Add params to open links in new tab

[Library-Header] Add params to open links in new tab

---

src/Smart.Design.Library/README.md
src/Smart.Design.Library/Smart.Design.Library.csproj

Re-add README to project library to be displayed on nuget.org page

Add Readme to Design library as embedded resource

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Components/GridList/GridList.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Components/GridListRow/GridListRow.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml

[JIRA description](https://smartjira.atlassian.net/browse/blip-6694)
Complete GridList page
Detailed list of changes/actions
* Complete the GridList page
* Note the GridListRow page
* Add bagde on left side menu

[Showcase]- GridList page

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Pagination/Pagination.cshtml

[Showcase] Pagination page
[JIRA description](https://smartjira.atlassian.net/browse/blip-6694)
Add missing C# Code and detailled parameters

[Showcase] Pagination page

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Grid/Grid.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Components/GridColumn/GridColumn.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml

[JIRA description](https://smartjira.atlassian.net/browse/6694)
- Complete the Grid component page
- Link the GridColumn component page
- Add badge in the left side menu

[Showcase] - Grid

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Select/Select.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml

[JIRA description](https://smartjira.atlassian.net/browse/blip-6694)
Detailed list of changes/actions
* change title page
* remove wrong description
* add badge in left side menu

[Showcase] - Select page correction

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Card/Card.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Components/CardActions/CardActions.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Components/CardBody/CardBody.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Components/CardTitle/CardTitle.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml

[JIRA description](https://smartjira.atlassian.net/browse/BLIP-6694)
- group Card part components pages to point to Card page

[Showcase] - Card page improvment

---

src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/TagHelpers/TableOfContent/TableOfContentHtmlGenerator.cs
src/Smart.Design.Library/wwwroot/css/main.css

https://smartjira.atlassian.net/browse/CURU-139
Delete not-numbered class
https://design.smart.coop/examples/template-examples/terms-and-conditions.html

[Library] Adapt table of content css

---

src/Smart.Design.Library/Smart.Design.Library.csproj

Add README.md to nuget packaging

[Library] Add readme to nuget

---

src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/wwwroot/css/main.css

https://smartjira.atlassian.net/browse/CURU-139
[Terms and conditions - Smart Design System](https://design.smart.coop/examples/template-examples/terms-and-conditions.html)

[Library] Fix css for ul in ol

---

src/Smart.Design.Library/Smart.Design.Library.csproj

[Library] Fix version

---

src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/wwwroot/css/main.css

[Library] Update css

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml.cs
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_Layout.cshtml

https://smartjira.atlassian.net/browse/PAIL-64
Add a log page in showcase.

[Showcase] Changelog page

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml

[[JIRA description](https://smartjira.atlassian.net/browse/XXXX)](https://smartjira.atlassian.net/browse/PAIL-80)

[Showcase]Last modifications on Subscription page

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Confirmation.cshtml

[[JIRA description](https://smartjira.atlassian.net/browse/XXXX)](https://smartjira.atlassian.net/browse/TT-69)

[Showcase] Comment showcase confirmation page

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Box/Box.cshtml.cs
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_Layout.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/ProductionUnit.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/ProductionUnit.cshtml.cs
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/_TemplatesIndex.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/_TemplatesIndex.cshtml.cs
src/Smart.Design.Library.Showcase.WebApp/wwwroot/css/main.css
src/Smart.Design.Library/Extensions/DependencyRegistration.cs
src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/TagHelpers/Box/BoxHtmlGenerator.cs
src/Smart.Design.Library/TagHelpers/Box/BoxTagHelper.cs
src/Smart.Design.Library/TagHelpers/Box/IBoxHtmlGenerator.cs
src/Smart.Design.Library/TagHelpers/Constants/TagNames.cs
src/Smart.Design.Library/wwwroot/css/main.css

https://smartjira.atlassian.net/browse/CURU-160
Create Box tag.
Implemented box tag in Unity Production page. (html from this [PR](https://github.com/smartcoop/design-library/pull/91))
https://design-showcase-stage.smartbe.be/Templates/ProductionUnit
https://www.figma.com/proto/Xg7VlIioBRfEGSN72297H4/Account?page-id=1758%3A41786&node-id=1758-41787&viewport=448%2C277%2C0.4&scaling=min-zoom

[Library/Showcase] Create Box tag and unity production page

---

src/Smart.Design.Library/Smart.Design.Library.csproj

[JIRA description](https://smartjira.atlassian.net/browse/BLIP-7214)

hotfix(BLIP-7214): [BE - DESIGN] Change version from 2.1.0-pre-release to 2.1.0

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Components/Select/Select.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Shared/_ComponentList.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
src/Smart.Design.Library/Smart.Design.Library.csproj

- Update documentation Select Taghelper
- Update select option for languages

 [Library/Nuget]-Upgrade package to 2.1.1

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Components/FormGroupTextArea/FormGroupTextArea.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml.cs
src/Smart.Design.Library/Extensions/PhoneNumberValidatorAttribute.cs
src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/TagHelpers/Elements/Input/InputHtmlGenerator.cs

[JIRA description]([BE - DESIGN] DL - champs "téléphone" bug)

hotfix(PAIL-98): [BE - DESIGN] DL - champs téléphone bug

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml
src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/TagHelpers/Header/HeaderHtmlGenerator.cs

https://smartjira.atlassian.net/browse/BLIP-7267
https://smartjira.atlassian.net/browse/BLIP-7268
Update header tag: 
- Delete main label 
- Question link

[Library] Adapt header tag

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Confirmation.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/_TemplatesIndex.cshtml
src/Smart.Design.Library.Showcase.WebApp/Smart.Design.Library.Showcase.csproj

[JIRA description](https://smartjira.atlassian.net/browse/PAIL-102)

feature(PAIL-65): Layout avec composants page inscription - succès

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml
src/Smart.Design.Library/Resources/Translations.Designer.cs
src/Smart.Design.Library/Resources/Translations.fr.resx
src/Smart.Design.Library/Resources/Translations.nl.resx
src/Smart.Design.Library/Resources/Translations.resx
src/Smart.Design.Library/Smart.Design.Library.csproj

https://smartjira.atlassian.net/browse/BLIP-7267
Change wording documentation

[Library] Adapt help tab in header tag

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml
src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/TagHelpers/Elements/Input/IInputHtmlGenerator.cs
src/Smart.Design.Library/TagHelpers/Elements/Input/InputHtmlGenerator.cs
src/Smart.Design.Library/TagHelpers/Elements/Input/InputNumberTagHelper.cs

…s input number (PP)
[JIRA description](https://smartjira.atlassian.net/browse/PAIL-111)

[BE - DESIGN] Solve decimal issues in input type number

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml
src/Smart.Design.Library/TagHelpers/Elements/Select/SelectHtmlGenerator.cs

[JIRA description](https://smartjira.atlassian.net/browse/PAIL-112)

[BE - DESIGN] Garder valeur du select + aperçu visuel lors d'une erreur

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Changelog.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/TagHelpers/Elements/Input/IInputHtmlGenerator.cs
src/Smart.Design.Library/TagHelpers/Elements/Input/InputHtmlGenerator.cs
src/Smart.Design.Library/TagHelpers/Elements/Input/InputNumberTagHelper.cs

[JIRA description](https://smartjira.atlassian.net/browse/PAIL-136)

feature(PAIL-136): [BE - DESIGN] Front: add parameters defaultValue, minimalValue + Add message in the div

---

src/Smart.Design.Library.Showcase.WebApp/README_GIT_GUIDELINE.md
src/Smart.Design.Library/README_GIT_GUIDELINE.md

[JIRA description](https://smartjira.atlassian.net/browse/PAIL-174)

feature(PAIL-174): TT-DL · Readme Git guideline design library

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Subscription.cshtml
src/Smart.Design.Library/Smart.Design.Library.csproj
src/Smart.Design.Library/TagHelpers/Alert/AlertHtmlGenerator.cs

https://smartjira.atlassian.net/browse/BLIP-7771
For the subscription form, we may need to display links in the error list messages. An example is added to the showcase template to display usage of this change.
Update  package version.

[Library/Showcase] Display list of error messages in raw html

---

src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Dialog/DialogTest.cshtml
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/Dialog/DialogTest.cshtml.cs
src/Smart.Design.Library.Showcase.WebApp/Pages/Templates/_TemplatesIndex.cshtml

https://smartjira.atlassian.net/browse/BLIP-7870

Create Telerik dialog box
